FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y ruby-full ruby-dev build-essential && \
    apt-get --assume-yes install apt-transport-https ca-certificates && \
    gem install bundler --no-ri --no-rdoc

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY Gemfile* $APP_HOME/
COPY . $APP_HOME
RUN bundle install
ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292
CMD ["puma"]
